# this file was not auto-generated by created manually by lin,leo

from django.conf.urls import url

from . import views

urlpatterns = [

    #url(r'', views.catalog_home, name='catalog_home' ),
    url(r'^$', views.index, name='index'),  ### name='index' is used for reverse url mapping scenarios
                                          ### for example, <a href='{% url 'index' %}'> Home </a>

    ### match /catalog/books/$
    ### instead of creating our own implementation of view, by query the models
    ### and then call 'render()' to pass the list to a specified template, we use a generic
    ### django class-based list view (ListView) - a class that inherits from an existing view.
    ### it has all if not most of the functionality that we need, and followe Django best-practices.for
    ### see catalog/views.py BookListView() class
    url(r'^books/$', views.BookListView.as_view(), name='books'),

    ### match /catalog/book/<pk=pk>
    ### regex (?P<pk>\d+)$ capture the |d+ value and send it as pk='d'
    ### for example, 'book/1234' will send the variable pk='1234' to the view
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
]